name: 'cicd-0.1'

networks:
  cicd_net:
    external: false

# Примеры развёртывания Redmine
# https://hub.docker.com/_/redmine
# https://github.com/sameersbn/docker-redmine/blob/master/docker-compose-mysql.yml
services:

  gitea:
    container_name: gitea
    image: gitea/gitea:${GITEA_VERSION:-1.22.6}
    restart: unless-stopped
    environment:
      # https://docs.gitea.io/en-us/install-with-docker/#environments-variables
      - APP_NAME="Gitea"
      - USER_UID=1000
      - USER_GID=1000
      - RUN_MODE=prod
      - DOMAIN=${IP_ADDRESS}
      - SSH_DOMAIN=${IP_ADDRESS}
      - HTTP_PORT=3000
      - ROOT_URL=http://${IP_ADDRESS}:3000
      - SSH_PORT=222
      - SSH_LISTEN_PORT=22
      - DB_TYPE=sqlite3
    ports:
      - "3000:3000"
      - "222:22"
    networks:
      - cicd_net
    volumes:
      - ./storage/gitea:/data

  drone:
    container_name: drone
    image: drone/drone:${DRONE_VERSION:-1.6.4}
    restart: unless-stopped
    depends_on:
      - gitea
    environment:
      # https://docs.drone.io/server/provider/gitea/
      - DRONE_DATABASE_DRIVER=sqlite3
      - DRONE_DATABASE_DATASOURCE=/data/database.sqlite
      - DRONE_GITEA_SERVER=http://${IP_ADDRESS}:3000/
      - DRONE_GIT_ALWAYS_AUTH=false
      - DRONE_RPC_SECRET=${DRONE_RPC_SECRET}
      - DRONE_SERVER_PROTO=http
      - DRONE_SERVER_HOST=${IP_ADDRESS}:3001
      - DRONE_TLS_AUTOCERT=false
      - DRONE_USER_CREATE=${DRONE_USER_CREATE}
      - DRONE_GITEA_CLIENT_ID=${DRONE_GITEA_CLIENT_ID}
      - DRONE_GITEA_CLIENT_SECRET=${DRONE_GITEA_CLIENT_SECRET}
    ports:
      - "3001:80"
      - "9001:9000"
    networks:
      - cicd_net
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./drone:/data

  drone-runner:
    container_name: drone-runner
    image: drone/drone-runner-docker:${DRONE_RUNNER_VERSION:-latest}
    restart: unless-stopped
    depends_on:
      - drone
    environment:
      # https://docs.drone.io/runner/docker/installation/linux/
      # https://docs.drone.io/server/metrics/
#      - DRONE_RPC_PROTO=http
#      - DRONE_RPC_HOST=drone
#      - DRONE_RPC_SECRET=${DRONE_RPC_SECRET}
#      - DRONE_RUNNER_NAME="${HOSTNAME}-runner"
#      - DRONE_RUNNER_CAPACITY=2
#      - DRONE_RUNNER_NETWORKS=cicd_net
#      - DRONE_DEBUG=false
#      - DRONE_TRACE=false
      - DRONE_RPC_HOST=drone
      - DRONE_RPC_PROTO=http
      - DRONE_RPC_SECRET=bea26a2221fd8090ea38720fc445eca6
      - DRONE_TMATE_ENABLED=true
    ports:
      - "3002:3000"
    networks:
      - cicd_net
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  redmine:
    image: redmine
#    restart: always
    depends_on:
      - redmine-db
    ports:
      - "8080:3000"
    volumes:
      - ./storage/docker_redmine-plugins:/usr/src/redmine/plugins
      - ./storage/docker_redmine-themes:/usr/src/redmine/public/themes
      - ./storage/docker_redmine-data:/usr/src/redmine/files
      - ./storage/docker_redmine-logs:/var/log/redmine
    environment:
      - DB_ADAPTER=mysql2
      - DB_ENCODING=utf8mb4
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_USER=redmine
      - DB_PASS=password
      - DB_NAME=redmine_production

      - REDMINE_PORT=8080
      - REDMINE_HTTPS=false

  redmine-db:
    image: mysql:8.0
    restart: always
    environment:
      - MYSQL_USER=redmine
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=redmine_production
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
    volumes:
      - ./storage/docker_mysql-data:/var/lib/mysql
    # https://www.redmine.org/projects/redmine/wiki/MySQL_configuration
    command: --transaction-isolation=READ-COMMITTED
    cap_add:
      - SYS_NICE  # CAP_SYS_NICE
