name: 'cicd-0.1'

# Примеры развёртывания Redmine
# https://hub.docker.com/_/redmine
# https://github.com/sameersbn/docker-redmine/blob/master/docker-compose-mysql.yml
services:

  redmine:
    image: redmine
#    restart: always
    depends_on:
      - redmine-db
    ports:
      - "8080:3000"
    volumes:
      - ./storage/docker_redmine-plugins:/usr/src/redmine/plugins
      - ./storage/docker_redmine-themes:/usr/src/redmine/public/themes
      - ./storage/docker_redmine-data:/usr/src/redmine/files
      - ./storage/docker_redmine-logs:/var/log/redmine
    environment:
      - DB_ADAPTER=mysql2
      - DB_ENCODING=utf8mb4
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_USER=redmine
      - DB_PASS=password
      - DB_NAME=redmine_production

      - REDMINE_PORT=8080
      - REDMINE_HTTPS=false

  redmine-db:
    image: mysql:8.0
    restart: always
    environment:
      - MYSQL_USER=redmine
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=redmine_production
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
    volumes:
      - ./storage/docker_mysql-data:/var/lib/mysql
    # https://www.redmine.org/projects/redmine/wiki/MySQL_configuration
    command: --transaction-isolation=READ-COMMITTED
    cap_add:
      - SYS_NICE  # CAP_SYS_NICE